services:

  mysql:
    image: mysql:8
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql   #
    networks:
      - shopsphere-network

  discovery-service:
    image: discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - shopsphere-network


  kafka:
   image: apache/kafka:4.0.2
   container_name: kafka-container
   ports:
     - "9092:9092"

   networks:
    - shopsphere-network

networks:

  shopsphere-network:

volumes:
  mysql_data: