spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://mysql-container:3306/users_db
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: ${JWT_KEY:mysupersecretkeymysupersecretkey123}
  expiration: 60000000

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
      fetch-registry: true
      register-with-eureka: true
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html